In [1]:
import pandas as pd
import numpy as np

Working with JSON

In [3]:
df=pd.read_json("https://api.sampleapis.com/jokes/goodJokes")
df.head()

,id,type,setup,punchline
0,1,general,What did the fish say when it hit the wall?,Dam.
1,2,general,How do you make a tissue dance?,You put a little boogie on it.
2,3,general,What's Forrest Gump's password?,1Forrest1
3,4,general,What do you call a belt made out of watches?,A waist of time.
4,5,general,Why can't bicycles stand on their own?,They are two tired

Working with SQL

In [6]:
import mysql.connector

In [10]:
conn= mysql.connector.connect(host="localhost", user="root", password="", database='world')

In [25]:
df= pd.read_sql_query("SELECT * from city where CountryCode LIKE 'USA'", conn)
df.head()

C:\Users\adhik\AppData\Local\Temp\ipykernel_13648\310515089.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df= pd.read_sql_query("SELECT * from city where CountryCode LIKE 'USA'", conn)

     ID          Name CountryCode      District  Population
0  3793      New York         USA      New York     8008278
1  3794   Los Angeles         USA    California     3694820
2  3795       Chicago         USA      Illinois     2896016
3  3796       Houston         USA         Texas     1953631
4  3797  Philadelphia         USA  Pennsylvania     1517550